---
name: Bazel build

# env:
#   HTTP_PROXY: http://10.0.0.9:3128/
#   HTTPS_PROXY: http://10.0.0.9:3128/

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - reopened
  push:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ self-macos-amd64 ]
        os: [macos-latest]

    steps:
      -
        name: Date-Based Cache key
        # get a key showing the current week (ISO: yyyyWww) allowing older caches to age-out/autoprune
        id: week
        run: echo "::set-output name=iso::$(date +'bazel-%YW%U')"
      -
        uses: bazel-contrib/setup-bazel@0.14.0
        with:
          # Cache bazel downloads via bazelisk
          bazelisk-cache: true
          # Store build cache per week
          disk-cache: ${{ steps.week.outputs.iso }}
          # Share repository cache between workflows.
          repository-cache: true
      -
        name: Clone Repo
        uses: actions/checkout@v4
      # - run: echo "/usr/local/bin" >> $GITHUB_PATH  # uses local python3 as chicken-and-egg resolver, needs to be in path
      -
        run: bazel build //...
      # - run: bazel test //... --test_output=errors --test_summary=detailed
      -
        run: bazel shutdown
